# Generated by Django 3.2.5 on 2021-07-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='date_of_birth',
            field=models.CharField(max_length=30),
        ),
    ]
