# Generated by Django 3.2.5 on 2021-07-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterField(
            model_name='followers',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
