# Generated by Django 3.2.5 on 2021-07-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210711_0756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
