# Generated by Django 3.2.5 on 2021-07-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='emila',
            new_name='email',
        ),
    ]
